mysql:
  host: "127.0.0.1"
  port: "3308"
  dbname: testdb
  username: root
  password: 123456
  charset: utf8mb4

config:
  ruler:
    邮箱: '\w[-\w.+]*@([A-Za-z0-9][-A-Za-z0-9]+\.)+[A-Za-z]{2,14}'
    身份证: '^(\d{6})(\d{4})(\d{2})(\d{2})(\d{3})([0-9]|X)$'
    电话号码(座机): '\d{3}-\d{8}|\d{4}-\{7,8}'
    手机号码: "0?(13|14|15|18|17)[0-9]{9}"
    IP地址: '(25[0-5]|2[0-4]\d|[0-1]\d{2}|[1-9]?\d)\.(25[0-5]|2[0-4]\d|[0-1]\d{2}|[1-9]?\d)\.(25[0-5]|2[0-4]\d|[0-1]\d{2}|[1-9]?\d)\.(25[0-5]|2[0-4]\d|[0-1]\d{2}|[1-9]?\d)'
